https://plantuml.com/de/state-diagram

@startuml
hide empty description

[*] --> NightlyCronJob

NightlyCronJob : user.account.deleteworkflow.cron
NightlyCronJob --> DeleteUserAccountScheduler : triggers

note right of NightlyCronJob : Configured in application.properties

DeleteUserAccountScheduler --> DeleteUserAccountService : executes

state DeleteUserAccountService #lightblue {
  [*] --> CollectDeletedUsers
  CollectDeletedUsers --> DeleteAskerActions : executes
  [*] --> CollectDeletedConsultants
  CollectDeletedConsultants --> DeleteConsultantActions : executes
  WorkflowErrors --> WorkflowErrorMailService

  state DeleteAskerActions {
    DeleteKeycloakAskerAction --> DeleteAskerRoomsAndSessionsAction
    DeleteAskerRoomsAndSessionsAction --> DeleteDatabaseAskerAgencyAction
    DeleteDatabaseAskerAgencyAction --> DeleteRocketChatAskerAction
    DeleteRocketChatAskerAction --> DeleteDatabaseAskerAction
    DeleteDatabaseAskerAction --> WorkflowErrors : collect all errors
  }

  state DeleteConsultantActions {
      DeleteKeycloakConsultantAction --> DeleteDatabaseConsultantAgencyAction
      DeleteDatabaseConsultantAgencyAction --> DeleteChatAction
      DeleteChatAction --> DeleteRocketChatConsultantAction
      DeleteRocketChatConsultantAction --> DeleteDatabaseConsultantAction
      DeleteDatabaseConsultantAction  --> WorkflowErrors : collect all errors
  }
}

state WorkflowErrorMailService {
  BuildOneMailContainingAllErrors --> sendToMailService
}
@enduml
